version: '3.4'

networks: 
  webapp:
    driver: bridge

services:

  postgres_srv:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    networks: 
      - webapp

  handyapp:
    image: handyapp
    env_file:
      - .env
    depends_on:
      - "postgres_srv"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8443:80"
      - "7777:5432"
    environment:
      DB_CONNECTION_STRING: "host=postgres_srv;port=5432;database=${DB_NAME};username=${DB_USER};password=${DB_PASSWORD}"
      TELEGRAM_API_TOKEN: "${TELEGRAM_API_TOKEN}"
      APP_URL: "${APP_URL}"
      TELEGRAM_WEBHOOK_URL: "${TELEGRAM_WEBHOOK_URL}"
      JWT_SECURITY_KEY: "${JWT_SECURITY_KEY}"
      JWT_EXPIRATION_TIME: "${JWT_EXPIRATION_TIME}"
    networks:
      - webapp
    
  # frontend:
  #   image: nginx:latest
  #   ports:
  #     - "9000:80"
  #   volumes:
  #     - ./frontend:/usr/share/nginx/html

volumes:
  db_volume: